# Path to EasyNPC Profile.log file
EasyNpcProfilePath = "~/AppData/Local/EasyNPC/Profile.log"

# List of plugins to exclude from RSV (NPCs using these face plugins will be excluded)
ExcludePlugins = [
  "Karura's Ordinary People Refined.esp",
  "MOSRefined.esp",
  "MOSRefinedDawnguard.esp",
  "MOSRefinedDragonborn.esp",
  "TDOSRefined.esp",
  "TSOSRefined.esp",
  "TSOSRefinedDawnguard.esp",
  "TSOSRefinedDragonborn.esp",
  "TSOSRefinedHearthfire.esp"
]

